"""Registration info

Revision ID: 239c3e89951
Revises: 4afa2377cc4
Create Date: 2015-02-02 00:58:20.194310

"""

# revision identifiers, used by Alembic.
revision = '239c3e89951'
down_revision = '4afa2377cc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('allergies', sa.String(), nullable=True))
    op.add_column('users', sa.Column('shirt_size', sa.Enum('S', 'M', 'L', 'XL', 'XXL', native_enum=False, name='shirt_size_name'), nullable=False))
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    op.drop_column('users', 'shirt_size')
    op.drop_column('users', 'allergies')
    op.drop_table('teams')
    ### end Alembic commands ###
