"""Remove admin field for is_admin

Revision ID: b2ca1549f4
Revises: 239c3e89951
Create Date: 2015-02-02 01:05:10.248906

"""

# revision identifiers, used by Alembic.
revision = 'b2ca1549f4'
down_revision = '239c3e89951'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'admin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_admin')
    ### end Alembic commands ###
