"""Add team uuid

Revision ID: 428749a1f09
Revises: b2ca1549f4
Create Date: 2015-02-02 22:39:32.139259

"""

# revision identifiers, used by Alembic.
revision = '428749a1f09'
down_revision = 'b2ca1549f4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('secret', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'teams', ['secret'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'secret')
    ### end Alembic commands ###
