"""Add user confirmation uuid

Revision ID: 56ed8b1d561
Revises: 428749a1f09
Create Date: 2015-02-02 22:56:05.732330

"""

# revision identifiers, used by Alembic.
revision = '56ed8b1d561'
down_revision = '428749a1f09'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['confirmation'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'confirmation')
    ### end Alembic commands ###
