"""Add icon_name column to User

Revision ID: 24804ad04c76
Revises: 56ed8b1d561
Create Date: 2015-02-03 10:12:38.639691

"""

# revision identifiers, used by Alembic.
revision = '24804ad04c76'
down_revision = '56ed8b1d561'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('icon_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'icon_name')
    ### end Alembic commands ###
