"""Add remote column to user

Revision ID: 247a7b9b6a05
Revises: 24804ad04c76
Create Date: 2015-02-24 05:39:27.718942

"""

# revision identifiers, used by Alembic.
revision = '247a7b9b6a05'
down_revision = '24804ad04c76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remote', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remote')
    ### end Alembic commands ###
