"""Add user location

Revision ID: 255e3d946e65
Revises: 247a7b9b6a05
Create Date: 2015-02-24 06:13:48.849926

"""

# revision identifiers, used by Alembic.
revision = '255e3d946e65'
down_revision = '247a7b9b6a05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.Enum('MTU', 'NMU', 'WMU', 'Sponsor', 'Other', native_enum=False, name='user_location'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    ### end Alembic commands ###
