"""Add remote to teams

Revision ID: 123a41b1e369
Revises: 255e3d946e65
Create Date: 2015-03-02 19:31:47.192527

"""

# revision identifiers, used by Alembic.
revision = '123a41b1e369'
down_revision = '255e3d946e65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('remote', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'remote')
    ### end Alembic commands ###
