"""update team

Revision ID: 1e3bbda95841
Revises: 123a41b1e369
Create Date: 2015-03-02 19:02:19.982540

"""

# revision identifiers, used by Alembic.
revision = '1e3bbda95841'
down_revision = '123a41b1e369'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('location', sa.Enum('MTU', 'NMU', 'WMU', 'Sponsor', native_enum=False, name='team_location'), nullable=False))
    op.drop_column('teams', 'remote')
    op.drop_column('users', 'remote')
    op.drop_column('users', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('teams', 'location')
    ### end Alembic commands ###
