"""Fix food preferences

Revision ID: 6a8353cdac4
Revises: 1e3bbda95841
Create Date: 2015-03-02 21:12:46.013334

"""

# revision identifiers, used by Alembic.
revision = '6a8353cdac4'
down_revision = '1e3bbda95841'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('food_other', sa.String(), nullable=True))
    op.add_column('users', sa.Column('food_preferences', sa.Enum('None',
        'Vegetarian', 'Vegan', 'Gluten Free', 'Other', native_enum=False, name='food_preferences_types'), nullable=False))
    op.drop_column('users', 'allergies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allergies', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'food_preferences')
    op.drop_column('users', 'food_other')
    ### end Alembic commands ###
